steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/admin-app:$COMMIT_SHA',
          '--build-arg', 'app_env_arg=prod',
          '--build-arg', 'instance_url_arg=${_INSTANCE_URL}',
          '.' ]
- name: 'gcr.io/cloud-builders/kubectl'
  env: ['CLOUDSDK_COMPUTE_ZONE=us-east1-b', 'CLOUDSDK_CONTAINER_CLUSTER=demo-cluster']
  args: ['set', 'image', 'deployment/demo-admin-app',
          'admin-app=gcr.io/$PROJECT_ID/admin-app:$COMMIT_SHA']
images:
- 'gcr.io/$PROJECT_ID/admin-app:$COMMIT_SHA'
