steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/admin-app:$COMMIT_SHA-nv',
          '--build-arg', 'app_env_arg=prod',
          '--build-arg', 'instance_url_arg=http://clinicanv.org',
          '.' ]
- name: 'gcr.io/cloud-builders/kubectl'
  env: ['CLOUDSDK_COMPUTE_ZONE=us-east1-c', 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1']
  args: ['set', 'image', 'deployment/hikma-health-admin-app-nv',
          'admin-app=gcr.io/$PROJECT_ID/admin-app:$COMMIT_SHA-nv']
images:
- 'gcr.io/$PROJECT_ID/admin-app:$COMMIT_SHA-nv'
